version: '3'
services:
  api:
    build:
      context: ./API
      #dockerfile: API/production.Dockerfile
      dockerfile: API/development.Dockerfile
      args:
        LOCAL_PORT: ${LOCAL_PORT}
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${LOCAL_PORT:-8000}:${LOCAL_PORT:-8000}"
    depends_on:
      - db
  mqtt:
    build:
      context: ./MQTT
      dockerfile: Dockerfile
      args:
        MQTT_PORT: ${MQTT_PORT:-8001}
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${MQTT_PORT:-8001}:${MQTT_PORT:-8001}"
  db:
    image: postgres:12.8
    volumes:
      - postgres_data156513:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT:-5432}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"

volumes:
  postgres_data156513:
