version: '3'

# Común a todos los contenedores
x-defaults-container: &container-defaults
  restart: unless-stopped
  stop_grace_period: 3s

services:
  api:
    build:
      context: ./API
      dockerfile: production.Dockerfile
      args:
        API_PORT: ${API_PORT}
        NODE_VERSION: ${API_NODE_VERSION:-16}
    env_file:
      - .env
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    depends_on:
      - db
    <<: *container-defaults

  mqtt:
    build:
      context: ./MQTT
      dockerfile: production.Dockerfile
      args:
        MQTT_API_PORT: ${MQTT_API_PORT:-8001}
        NODE_VERSION: ${MQTT_API_NODE_VERSION:-16}
    env_file:
      - .env
    ports:
      - "${MQTT_API_PORT:-8001}:${MQTT_API_PORT:-8001}"
    <<: *container-defaults

  db:
    image: postgres:12.8
    volumes:
      - postgres_data1256513:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT:-5432}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    <<: *container-defaults

volumes:
  postgres_data1256513:
