version: '3'
services:
  api:
    build: ./API
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${LOCAL_PORT}:8000"
    depends_on:
      - db
  mqtt:
    build: ./MQTT
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${MQTT_PORT}:8001"
  db:
    image: postgres:12.8
    volumes:
      - postgres_data156513:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  postgres_data156513:
