version: '3'
services:
  api:
    build: ./API
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${LOCAL_PORT:-8000}:8000"
    depends_on:
      - db
  mqtt:
    build: ./MQTT
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${MQTT_PORT-8000}:8001"
  db:
    image: postgres:12.8
    volumes:
      - db/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT:-5432}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
