version: "3.8"

services:
#  api_workers:
#    container_name: api_workers
#    command: /bin/bash -c "/app/entrypoint.api.sh"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    expose:
#      - 8001
#    ports:
#      - 8001:8001
#    env_file:
#      - ./.env
#      #- ./template.env
#    restart: unless-stopped
#    depends_on:
#      - redis_workers

  celery_worker:
    container_name: celery_workers
    command: /bin/bash -c "/app/entrypoint.celery.sh"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
      #- ./template.env
    depends_on:
      - redis_workers
    restart: unless-stopped
    # TODO: Sacar
    volumes:
      - ./src:/app
    stop_grace_period: 5s

  pytest_worker:
    container_name: pytest_workers
    command: /bin/bash -c "/app/entrypoint.pytest.sh"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
      #- ./template.env
    depends_on:
      - redis_workers
      - celery_worker
      #- api_workers
    restart: no
    # TODO: Sacar
    volumes:
      - ./src:/app
    stop_grace_period: 5s

  redis_workers:
    container_name: redis_workers
    image: redis:7.2-alpine
    volumes:
      - 'redis:/var/lib/redis'
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  redis:
