name: CD API Workers

on:
  push:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install ssh
      run: sudo apt-get install openssh-client sshpass -y

    - name: Setup environment variables
      run: |
        echo "EC2HOST=arqui-workers.ljg.cl" >> $GITHUB_ENV
        echo "EC2PORT=22" >> $GITHUB_ENV
        echo "EC2USER=ubuntu" >> $GITHUB_ENV
        echo "EC2PASSWD=${{ secrets.EC2PASSWD }}" >> $GITHUB_ENV

    - name: Update and reload containers
      run: sshpass -p "${EC2PASSWD}" ssh -o StrictHostKeyChecking=no -p ${EC2PORT} ${EC2USER}@${EC2HOST} -Ct "cd /home/ubuntu/grupo19-backend/workers && git fetch && git reset --hard && git checkout main && git pull && chmod -R a+x . && sudo docker compose down && sudo docker system prune -a -f && sudo docker compose pull && sudo docker compose build --no-cache && sudo docker compose up -d"
