name: Node.js CI/CD Workflow

on:
  push:
    branches:
      - feat/ci
  pull_request:
    branches:
      - feat/ci

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cambiar al directorio API
      run: cd API

    - name: Setup environment variables
      run: |
        echo "DB_HOST=localhost" >> $GITHUB_ENV
        echo "DB_DIALECT=postgres" >> $GITHUB_ENV
        echo "DB_NAME=postgres" >> $GITHUB_ENV
        echo "DB_PORT=5432" >> $GITHUB_ENV
        echo "DB_USERNAME=${{ secrets.DB_USER }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV


    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        
    - name: Install dependencies
      run: npm install

    - name: Run database migrations
      run: npx sequelize-cli db:migrate

    - name: Run database seeds
      run: npx sequelize-cli db:seed:all

    - name: Run tests
      run: npm test
